FirstWeb/Controllers/FirstController.cs
using Microsoft.AspNetCore.Mvc;

namespace FirstWeb.Controllers;

public class FirstController : Controller
{
    [HttpGet]
    [Route("")] //we do not need leading slashes in these routes in C#
    public string Index()
    {
        return "<h1>Hello from our controller!</h1>";
    }

    [HttpGet("two")]
    public string PageTwo()
    {
        return "Yup this is page two!";
    }

    [HttpGet("params/{id}/{name}")]
    public string Params(int id, string name)
    {
        return $"{name} is id number {id}";
        
    }

    [HttpGet("view")]
    public ViewResult MyView()
    {
        ViewBag.Name = "Bob";
        ViewBag.Number = 10;
        ViewBag.Flavors = new List<string>(){"vanilla", "strawberry"};
        return View(); // we can leave out the view name if it matches the action name
        //return View("MyView");
    }

    [HttpGet("form")]
    public ViewResult MyForm()
    {
        return View();
    }

    // [HttpPost("process")]
    // public RedirectResult Process(string Name, int Passcode)
    // {
    //     Console.WriteLine($"Got credentials: {Name} {Passcode}");
    //     return Redirect("form");
        
    // }

    // [HttpPost("process")]
    // public RedirectToActionResult Process(string Name, int Passcode)
    // {
    //     Console.WriteLine($"Got credentials: {Name} {Passcode}");
    //     return RedirectToAction("MyForm");
        
    // }

    [HttpPost("process")]
    public IActionResult Process(string Name, int Passcode)
    {
        Console.WriteLine($"Got credentials: {Name} {Passcode}");
        if (Passcode == 1234)
        {
            return RedirectToAction("MyView");
        }
        return View("TryAgain");
        
    }


    [HttpGet("{**path}")]
    public string Lost()
    {
        return "I think you are lost!";
    }

}

FirstWeb/Views/First/MyForm.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Form</title>
    <link rel="stylesheet" href="~/css/bootstrap.css">
</head>
<body>
    <form action="/process" method="post">
        <label for="Name">Name:</label>
        <input type="text" name="Name">
        <label for="Passcode">Passcode:</label>
        <input type="number" name="Passcode">
        <button class="btn btn-primary">Submit</button>
    </form>
</body>
</html>

FirstWeb/Views/First/MyView.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My First View</title>
    <link rel="stylesheet" href="~/css/bootstrap.css">
</head>
<body>
    <div class="container">

    <h1>Now we're serving views 🥳</h1>
    @{
        List<string> Names = new(){"Bob","Alice","Alex Miller"};
            <p>@Names[0]</p>
            Names.Add("TestName");
            <p>@Names[3]</p>
    }

    @foreach (string name in Names)
    {
        if (name == "Alice")
        {
            <img src="~/img/cake.jpg" alt="cake">
           <p>Welcome, Alice! We're glad you made it!</p> 
        }
        <p>@(name + " Lastname")</p>
    }

    @foreach (string flavor in ViewBag.Flavors)
    {
        <p>@flavor</p>
    }

    @for (int i = 0; i < ViewBag.Number; i++)
    {
        <p>@ViewBag.Name</p>
    }
    </div>
</body>
</html>

FirstWeb/Views/First/TryAgain.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Ooops not right passcode</h1>
    <a href="/form">Form</a>
    @* <a asp-action="MyForm" asp-controller="First">Form Link Two</a> *@
</body>
</html>